In [1]:
import pandas as pd

In [8]:
table1 = pd.read_csv('E:\MLOPSDataBank\Listing\DL_ADS-728_Decrypted_data.txt')
table1.columns = ["sourcelisting"]

#table1['FileName'] =table1["sourcelisting"].str.split("\\").str[-1]
table1['FileName'] = table1["sourcelisting"].str.extract(r'(?!.*\\)(.*?).pdf.*')+".pdf"
table1=table1[['FileName']]
table1 = table1.dropna()
table1 = table1.head()

table1['Original_folder'] = "FX"+table1["FileName"].str.extract(r'.*?\_FX(.*?)_')
table1['Original_MailItemID'] = "MI"+table1["FileName"].str.extract(r'.*?\_MI(.*?)_')
table1['Original_Document'] = "DT"+table1["FileName"].str.extract(r'DT(.*?)_.*')


table1['original_json_page_number'] =table1["FileName"].str.split("_").str[-2]
table1['Original_CO_page_number'] = table1["FileName"].str.extract(r'.*?\_C(?:0|1|2|3|4)-(.*?).pdf.*')

table1['Original_C0_format'] = table1["FileName"].str.split("_").str[-1].str.split('.').str[0].str.split('-').str[0]

print("table1 -",table1.shape)
table1['mongo_pageid'] = table1['Original_MailItemID']+"_"+table1['original_json_page_number']+"_C0-"+table1['Original_CO_page_number']

table1 - (5, 7)

In [7]:
table1

,FileName,Original_folder,Original_MailItemID,Original_Document,original_json_page_number,Original_CO_page_number,Original_C0_format,mongo_pageid
62076,Tax Returns-MI2003679510_000047_C0-000001.pdf,NaN,NaN,NaN,000047,000001,C0,NaN
62078,Tax Returns-MI2003679510_000048_C0-000002.pdf,NaN,NaN,NaN,000048,000002,C0,NaN
62080,Tax Returns-MI2003679510_000049_C0-000003.pdf,NaN,NaN,NaN,000049,000003,C0,NaN
62082,Tax Returns-MI2003679510_000050_C0-000004.pdf,NaN,NaN,NaN,000050,000004,C0,NaN
62084,Tax Returns-MI2003679510_000051_C0-000005.pdf,NaN,NaN,NaN,000051,000005,C0,NaN
...,...,...,...,...,...,...,...,...
3520694,Tax Returns-MI2007567332_000405_C0-000059.pdf,NaN,NaN,NaN,000405,000059,C0,NaN
3520696,Tax Returns-MI2007567332_000406_C0-000060.pdf,NaN,NaN,NaN,000406,000060,C0,NaN
3520698,Tax Returns-MI2007567332_000407_C0-000061.pdf,NaN,NaN,NaN,000407,000061,C0,NaN
3520700,Tax Returns-MI2007567332_000408_C0-000062.pdf,NaN,NaN,NaN,000408,000062,C0,NaN
3520702,Tax Returns-MI2007567332_000409_C0-000063.pdf,NaN,NaN,NaN,000409,000063,C0,NaN